//	AltirraSDL - Font management for the Dear ImGui UI
//
//	Discovers installed fonts and TTF/OTF files under <exe>/fonts/, exposes a
//	user-facing UI font and a separate monospace font, persists the choice
//	to the registry under Windows-compatible keys (Console: Font* for the
//	mono font; UI: Font* for the UI font), and rebuilds the ImGui font
//	atlas at end-of-frame whenever the user changes a setting.
//
//	The Configure System "Fonts" page (RenderFontsCategory) lives in this
//	file as well so all font logic stays in one place.

#include <stdafx.h>
#include <SDL3/SDL.h>
#include <imgui.h>
#include <imgui_internal.h>
#include <vd2/system/vdtypes.h>
#include <vd2/system/VDString.h>
#include <vd2/system/registry.h>
#include <vd2/system/file.h>
#include <vd2/system/filesys.h>
#include <vd2/system/text.h>

#include <algorithm>
#include <cctype>
#include <cfloat>
#include <cstring>
#include <vector>
#include <set>

#ifdef ATUI_HAVE_FONTCONFIG
#include <fontconfig/fontconfig.h>
#endif

#include "ui_fonts.h"
#include "ui_font_metadata.h"
#ifdef ATUI_HAVE_FREETYPE
#include <misc/freetype/imgui_freetype.h>
#include "ui_font_freetype.h"
#endif
#include "logging.h"

// Embedded font blobs — generated by cmake/embed_font.cmake at build time.
// Always linked into the binary so the UI works on every platform without
// depending on a runtime fonts/ directory.
extern "C" {
	extern const unsigned char g_atFontRobotoMediumData[];
	extern const unsigned int  g_atFontRobotoMediumData_size;
	extern const unsigned char g_atFontFiraMonoRegularData[];
	extern const unsigned int  g_atFontFiraMonoRegularData_size;
	extern const unsigned char g_atFontMaterialIconsData[];
	extern const unsigned int  g_atFontMaterialIconsData_size;
}

// =========================================================================
// Discovered font records
// =========================================================================

struct ATFontFile {
	VDStringA family;     // e.g. "Roboto", "Fira Mono"
	VDStringA weight;     // e.g. "Regular", "Medium", "Bold", "Light", ...
	bool italic = false;
	bool monospaced = false;
	int fontIndex = 0;    // face within a TrueType/OpenType collection
	// Either a filesystem path, OR a "<builtin>" marker.  When mpBuiltinData
	// is non-null, the font is loaded from memory instead of disk and `path`
	// is just a human-readable label.
	VDStringA path;
	const unsigned char *mpBuiltinData = nullptr;
	unsigned int mBuiltinSize = 0;
};

static std::vector<ATFontFile> s_fontFiles;
static std::vector<VDStringA> s_uiFamilies;    // distinct, proportional first
static std::vector<VDStringA> s_monoFamilies;  // distinct, monospaced

// =========================================================================
// Active font configuration
// =========================================================================

namespace {
	constexpr const char *kDefaultUIFamily   = "Roboto";
	constexpr const char *kDefaultUIWeight   = "Medium";
	constexpr int         kDefaultUISize     = 11;   // points
	constexpr const char *kDefaultMonoFamily = "Fira Mono";
	constexpr const char *kDefaultMonoWeight = "Regular";
	constexpr int         kDefaultMonoSize   = 10;
}

static VDStringA s_uiFamily(kDefaultUIFamily);
static VDStringA s_uiWeight(kDefaultUIWeight);
static int       s_uiSize     = kDefaultUISize;

static VDStringA s_monoFamily(kDefaultMonoFamily);
static VDStringA s_monoWeight(kDefaultMonoWeight);
static int       s_monoSize   = kDefaultMonoSize;

static float s_contentScale = 1.0f;
static bool  s_dirty = false;
static bool  s_initialized = false;
static bool  s_nativeRenderer = false;

ImFont *g_pFontUI   = nullptr;
ImFont *g_pFontMono = nullptr;
ImFont *g_pFontIcon = nullptr;
static ImFont *s_fontHeading = nullptr;

// Icon font is loaded at a single, button-friendly pixel size.  Gaming
// Mode is the only consumer right now and renders icons inside 48–56dp
// buttons, so a 22dp glyph height looks balanced next to ~14dp body
// text without crowding the touch target.  Scaled by contentScale at
// atlas-build time the same way the UI/mono fonts are.
namespace {
	constexpr float kIconPointSize = 20.0f; // pt; ~26px @ 1.0 contentScale (96 DPI)
}

// =========================================================================
// Helpers
// =========================================================================

static bool EndsWithCI(const VDStringA& s, const char *suffix) {
	const size_t n = strlen(suffix);
	if (s.size() < n) return false;
	for (size_t i = 0; i < n; ++i) {
		char a = (char)tolower((unsigned char)s[s.size() - n + i]);
		char b = (char)tolower((unsigned char)suffix[i]);
		if (a != b) return false;
	}
	return true;
}

// Read actual SFNT metadata in both catalog and directory discovery paths.
static void AddFontFiles(const VDStringA& path) {
	if (!EndsWithCI(path, ".ttf") && !EndsWithCI(path, ".otf")
		&& !EndsWithCI(path, ".ttc") && !EndsWithCI(path, ".otc")) return;
	if (std::any_of(s_fontFiles.begin(), s_fontFiles.end(),
		[&](const ATFontFile& f) { return f.path == path; })) return;
	size_t size = 0;
	void *data = SDL_LoadFile(path.c_str(), &size);
	if (!data) return;
	const auto faces = ATUIReadFontMetadata(data, size, s_nativeRenderer);
	SDL_free(data);
	for (const auto& face : faces) {
		if (face.requiresNativeRenderer && !s_nativeRenderer) continue;
		ATFontFile rec;
		rec.family = face.family.c_str();
		rec.weight = face.style.c_str();
		rec.italic = face.italic;
		rec.monospaced = face.monospaced;
		rec.fontIndex = face.index;
		rec.path = path;
		s_fontFiles.push_back(std::move(rec));
	}
}

static void ScanFontDir(const VDStringA& dir) {
	// Recursive scan, including nested static font folders. We avoid VDDirectoryIterator
	// dependency and use SDL's enumerator since SDL3 is already linked.
	struct Ctx {
		VDStringA base;
		std::set<VDStringA> visited;
		int depth = 0;
		void Scan(const VDStringA& d) {
			// Limit recursive traversal even if a font directory contains a
			// symlink cycle. OS catalogs normally avoid scanning altogether.
			if (depth >= 32 || visited.size() >= 4096 || !visited.insert(d).second) return;
			++depth;
			SDL_EnumerateDirectoryCallback cb = [](void *ud, const char *dirname, const char *fname) -> SDL_EnumerationResult {
				auto *self = (Ctx *)ud;
				VDStringA full = VDStringA(dirname);
				if (!full.empty() && full[full.size()-1] != '/' && full[full.size()-1] != '\\')
					full += '/';
				full += fname;

				SDL_PathInfo info {};
				if (!SDL_GetPathInfo(full.c_str(), &info))
					return SDL_ENUM_CONTINUE;

				if (info.type == SDL_PATHTYPE_DIRECTORY) {
					self->Scan(full);
				} else if (info.type == SDL_PATHTYPE_FILE) {
					AddFontFiles(full);
				}
				return SDL_ENUM_CONTINUE;
			};
			SDL_EnumerateDirectory(d.c_str(), cb, this);
			--depth;
		}
	} ctx;
	ctx.base = dir;
	ctx.Scan(dir);
}

#ifdef ATUI_HAVE_FONTCONFIG
static bool DiscoverFontconfigFonts() {
	// Query the native service dynamically so portable builds still start
	// on systems without Fontconfig. No additional linked dependency.
	struct Library {
		SDL_SharedObject *handle = SDL_LoadObject("libfontconfig.so.1");
		~Library() { if (handle) SDL_UnloadObject(handle); }
	} library;
	if (!library.handle) return false;
#define ATUI_LOAD_FC(name) \
	auto name = reinterpret_cast<decltype(&::name)>(SDL_LoadFunction(library.handle, #name)); \
	if (!name) return false
	ATUI_LOAD_FC(FcInitLoadConfigAndFonts);
	ATUI_LOAD_FC(FcPatternCreate);
	ATUI_LOAD_FC(FcPatternAddBool);
	ATUI_LOAD_FC(FcObjectSetBuild);
	ATUI_LOAD_FC(FcFontList);
	ATUI_LOAD_FC(FcPatternGetString);
	ATUI_LOAD_FC(FcFontSetDestroy);
	ATUI_LOAD_FC(FcObjectSetDestroy);
	ATUI_LOAD_FC(FcPatternDestroy);
	ATUI_LOAD_FC(FcConfigDestroy);
#undef ATUI_LOAD_FC
	// Fontconfig includes system directories, user-installed fonts, and
	// custom directories configured by the OS. Names/styles come from the
	// font metadata, not filenames; collection faces keep their own index.
	FcConfig *config = FcInitLoadConfigAndFonts();
	if (!config) return false;
	const size_t before = s_fontFiles.size();
	FcPattern *pattern = FcPatternCreate();
	if (pattern) FcPatternAddBool(pattern, FC_SCALABLE, FcTrue);
	FcObjectSet *objects = FcObjectSetBuild(FC_FILE, nullptr);
	FcFontSet *fonts = pattern && objects ? FcFontList(config, pattern, objects) : nullptr;
	if (fonts) {
		for (int i = 0; i < fonts->nfont; ++i) {
			FcPattern *font = fonts->fonts[i];
			FcChar8 *path = nullptr;
			if (FcPatternGetString(font, FC_FILE, 0, &path) == FcResultMatch)
				AddFontFiles(VDStringA((const char *)path));
		}
		FcFontSetDestroy(fonts);
	}
	if (objects) FcObjectSetDestroy(objects);
	if (pattern) FcPatternDestroy(pattern);
	FcConfigDestroy(config);
	return s_fontFiles.size() > before;
}
#endif

static void DiscoverSystemFonts() {
#ifdef ATUI_HAVE_FONTCONFIG
	if (DiscoverFontconfigFonts()) return;
#endif
#if defined(__APPLE__)
	ScanFontDir(VDStringA("/System/Library/Fonts"));
	ScanFontDir(VDStringA("/Library/Fonts"));
	if (const char *home = SDL_getenv("HOME")) {
		VDStringA userDir(home);
		userDir += "/Library/Fonts";
		ScanFontDir(userDir);
	}
#elif defined(__linux__) && !defined(__ANDROID__)
	ScanFontDir(VDStringA("/usr/share/fonts"));
	ScanFontDir(VDStringA("/usr/local/share/fonts"));
	if (const char *dataHome = SDL_getenv("XDG_DATA_HOME")) {
		VDStringA userDir(dataHome);
		userDir += "/fonts";
		ScanFontDir(userDir);
	}
	if (const char *home = SDL_getenv("HOME")) {
		VDStringA userDir(home);
		userDir += "/.fonts";
		ScanFontDir(userDir);
		if (!SDL_getenv("XDG_DATA_HOME")) {
			userDir = home;
			userDir += "/.local/share/fonts";
			ScanFontDir(userDir);
		}
	}
#endif
}

static void RebuildFamilyLists() {
	s_uiFamilies.clear();
	s_monoFamilies.clear();
	for (const auto& f : s_fontFiles) {
		if (std::find(s_uiFamilies.begin(), s_uiFamilies.end(), f.family) == s_uiFamilies.end())
			s_uiFamilies.push_back(f.family);
		if (f.monospaced && std::find(s_monoFamilies.begin(), s_monoFamilies.end(), f.family) == s_monoFamilies.end())
			s_monoFamilies.push_back(f.family);
	}
	std::sort(s_uiFamilies.begin(), s_uiFamilies.end());
	std::sort(s_monoFamilies.begin(), s_monoFamilies.end());
	// If there are no monospaced families discovered, fall back to UI list
	// so the user always has *something* to pick.
	if (s_monoFamilies.empty())
		s_monoFamilies = s_uiFamilies;
}

// Pick the best file for the requested (family, weight) pair.  Falls back
// to Regular weight, then any file in the family, then the role's bundled font.
static const ATFontFile *PickFontFile(const char *family, const char *weight,
	size_t builtinIndex = 0) {
	const ATFontFile *exact = nullptr, *familyRegular = nullptr, *anyInFamily = nullptr;
	for (const auto& f : s_fontFiles) {
		if (f.family != family) continue;
		if (!anyInFamily) anyInFamily = &f;
		if (f.weight == "Regular") familyRegular = &f;
		if (f.weight == weight) { exact = &f; break; }
	}
	if (exact) return exact;
	if (familyRegular) return familyRegular;
	if (anyInFamily) return anyInFamily;
	return s_fontFiles.size() > builtinIndex ? &s_fontFiles[builtinIndex] : nullptr;
}

// =========================================================================
// Atlas (re)build
// =========================================================================

// Build a static glyph range covering Latin-1, Latin Extended, Greek, and
// Cyrillic via ImFontGlyphRangesBuilder.  Persistent storage is required
// because ImGui keeps the pointer until the atlas is built.
static const ImWchar *GetUIFontGlyphRanges() {
	static ImVector<ImWchar> ranges;
	if (ranges.empty()) {
		ImFontGlyphRangesBuilder builder;
		ImFontAtlas *atlas = ImGui::GetIO().Fonts;
		builder.AddRanges(atlas->GetGlyphRangesDefault());   // Basic Latin + Latin-1
		builder.AddRanges(atlas->GetGlyphRangesCyrillic());  // ~400 Cyrillic glyphs
		builder.AddRanges(atlas->GetGlyphRangesGreek());     // Greek + Coptic
		// Latin Extended-A and Extended-B (Western/Central European accents
		// not covered by Latin-1: ą ć ę ł ń ś ź ż ř š č etc.)
		static const ImWchar kLatinExt[] = { 0x0100, 0x024F, 0 };
		builder.AddRanges(kLatinExt);
		// General Punctuation (en-dash, em-dash, smart quotes, ellipsis,
		// bullet, trade/service marks) — common in game pack file names.
		static const ImWchar kPunctuation[] = { 0x2000, 0x206F, 0 };
		builder.AddRanges(kPunctuation);
		// Letterlike Symbols (trademark ™ etc.)
		static const ImWchar kLetterlike[] = { 0x2100, 0x214F, 0 };
		builder.AddRanges(kLetterlike);
		builder.BuildRanges(&ranges);
	}
	return ranges.Data;
}

// Mono font: keep the atlas small — debugger panes display ASCII + a few
// box-drawing chars.  Default range (Basic Latin + Latin-1) is enough.
static const ImWchar *GetMonoFontGlyphRanges() {
	return ImGui::GetIO().Fonts->GetGlyphRangesDefault();
}

// Material Icons font: every glyph lives in the BMP Private Use Area
// (U+E000..U+F8FF).  Loading the full range adds ~2,200 glyphs to the
// atlas — about 350 KB of texture at 22dp on a standard-density screen,
// which is acceptable for the one-time atlas build and keeps every
// ICON_MD_* macro from altirra_icons.h immediately available.
static const ImWchar *GetIconFontGlyphRanges() {
	static const ImWchar kIconRange[] = { 0xE000, 0xF8FF, 0 };
	return kIconRange;
}

static void LoadFontFromFile(const ATFontFile *file, float pixelSize,
	const ImWchar *glyphRanges, ImFont*& out, bool merge = false)
{
	out = nullptr;
	if (!file) return;

	const void *srcData = nullptr;
	size_t srcSize = 0;
	void *sdlData = nullptr;

	if (file->mpBuiltinData) {
		// Embedded blob — point at the linker-provided data directly.
		srcData = file->mpBuiltinData;
		srcSize = file->mBuiltinSize;
	} else {
		sdlData = SDL_LoadFile(file->path.c_str(), &srcSize);
		if (!sdlData || srcSize == 0) {
			LOG_INFO("UI", "Font load failed: %s", file->path.c_str());
			if (sdlData) SDL_free(sdlData);
			return;
		}
		srcData = sdlData;
	}

	// Always copy through ImGui's allocator so FontDataOwnedByAtlas can
	// safely IM_FREE() it later.  Embedded data must NOT be freed; copying
	// keeps that ownership invariant simple.
	void *imgData = IM_ALLOC(srcSize);
	memcpy(imgData, srcData, srcSize);
	if (sdlData) SDL_free(sdlData);

	ImFontConfig cfg;
	cfg.FontDataOwnedByAtlas = true;
	cfg.FontNo = file->fontIndex;
	cfg.MergeMode = merge;

	ImGuiIO& io = ImGui::GetIO();
	out = io.Fonts->AddFontFromMemoryTTF(imgData, (int)srcSize, pixelSize, &cfg, glyphRanges);
}

// Load the embedded Material Icons blob at `pixelSize`.  Returns the
// font through `out`.  Self-contained (no ATFontFile rec needed) because
// the icon font is never user-selectable.
static void LoadIconFontFromMemory(float pixelSize, ImFont*& out) {
	out = nullptr;
	if (!g_atFontMaterialIconsData || g_atFontMaterialIconsData_size == 0) {
		LOG_INFO("UI", "Icon font blob unavailable");
		return;
	}
	void *imgData = IM_ALLOC(g_atFontMaterialIconsData_size);
	memcpy(imgData, g_atFontMaterialIconsData, g_atFontMaterialIconsData_size);

	ImFontConfig cfg;
	cfg.FontDataOwnedByAtlas = true;
	// Icon glyphs are square; ask ImGui to pixel-snap horizontal advance
	// so they align cleanly to the integer grid the buttons draw on.
	cfg.PixelSnapH = true;
	// Material Icons font has tight side-bearings; nudge slightly to
	// match the visual baseline of the body text when drawn side by side.
	cfg.GlyphOffset = ImVec2(0.0f, 1.0f);

	ImGuiIO& io = ImGui::GetIO();
	out = io.Fonts->AddFontFromMemoryTTF(imgData,
		(int)g_atFontMaterialIconsData_size, pixelSize,
		&cfg, GetIconFontGlyphRanges());
}

static void RebuildAtlas() {
	ImGuiIO& io = ImGui::GetIO();
	io.Fonts->Clear();

	const float uiPx   = (float)s_uiSize   * s_contentScale * 96.0f / 72.0f;
	const float monoPx = (float)s_monoSize * s_contentScale * 96.0f / 72.0f;
	const float iconPx = kIconPointSize    * s_contentScale * 96.0f / 72.0f;

	LOG_INFO("UI", "Font rebuild: uiSize=%d monoSize=%d contentScale=%.2f uiPx=%.1f monoPx=%.1f iconPx=%.1f FontGlobalScale=%.2f",
		s_uiSize, s_monoSize, s_contentScale, uiPx, monoPx, iconPx, ImGui::GetIO().FontGlobalScale);

	const ATFontFile *uiFile   = PickFontFile(s_uiFamily.c_str(),   s_uiWeight.c_str());
	const ATFontFile *monoFile = PickFontFile(s_monoFamily.c_str(), s_monoWeight.c_str(), 1);

	LoadFontFromFile(uiFile,   uiPx,   GetUIFontGlyphRanges(),   g_pFontUI);
	if (!g_pFontUI)
		LoadFontFromFile(&s_fontFiles[0], uiPx, GetUIFontGlyphRanges(), g_pFontUI);
	ImFont *merged = nullptr;
	if (g_pFontUI && uiFile != &s_fontFiles[0])
		LoadFontFromFile(&s_fontFiles[0], uiPx, GetUIFontGlyphRanges(), merged, true);
	LoadFontFromFile(monoFile, monoPx, GetMonoFontGlyphRanges(), g_pFontMono);
	if (!g_pFontMono)
		LoadFontFromFile(&s_fontFiles[1], monoPx, GetMonoFontGlyphRanges(), g_pFontMono);
	if (g_pFontMono && monoFile != &s_fontFiles[1])
		LoadFontFromFile(&s_fontFiles[1], monoPx, GetMonoFontGlyphRanges(), merged, true);
	LoadFontFromFile(PickFontFile(s_uiFamily.c_str(), "Bold"), uiPx,
		GetUIFontGlyphRanges(), s_fontHeading);
	if (s_fontHeading)
		LoadFontFromFile(&s_fontFiles[0], uiPx, GetUIFontGlyphRanges(), merged, true);
	LoadIconFontFromMemory(iconPx, g_pFontIcon);

	if (!g_pFontUI) {
		// Last-resort fallback: ImGui's built-in ProggyClean bitmap font.
		// Reached only if every TTF (including the embedded one) failed
		// to load, e.g. due to memory pressure or a corrupted blob.
		LOG_INFO("UI", "All TTF fonts failed to load — using ProggyClean fallback");
		g_pFontUI = io.Fonts->AddFontDefault();
	}
	if (!g_pFontMono) {
		g_pFontMono = g_pFontUI;
	}
	if (!s_fontHeading) s_fontHeading = g_pFontUI;
	// g_pFontIcon may legitimately be null if the icon blob failed to
	// load — callers must always null-check before drawing with it.

	io.FontDefault = g_pFontUI;
	// ImGui 1.92 retains FontSizeBase after the first NewFrame. Replacing
	// FontDefault alone changes the face but leaves menus at the old size.
	ImGui::GetStyle().FontSizeBase = g_pFontUI->LegacySize;
	// ImGui 1.92 renderer backends build and upload the dynamic atlas on
	// their next NewFrame.  Calling Build() here marks all glyphs as
	// preloaded and conflicts once RendererHasTextures is enabled.
}

// =========================================================================
// Registry I/O
// =========================================================================

static const char *kRegPath = "Settings";

static void LoadFromRegistry() {
	VDRegistryAppKey key(kRegPath, false);

	VDStringW tmp;
	if (key.getString("UI: Font family", tmp))
		s_uiFamily = VDTextWToU8(tmp);
	if (key.getString("UI: Font weight", tmp))
		s_uiWeight = VDTextWToU8(tmp);
	int v = key.getInt("UI: Font point size tenths", 0);
	if (v > 0) s_uiSize = std::clamp(v / 10, 8, 32);

	if (key.getString("Console: Font family", tmp))
		s_monoFamily = VDTextWToU8(tmp);
	if (key.getString("Console: Font weight", tmp))
		s_monoWeight = VDTextWToU8(tmp);
	v = key.getInt("Console: Font point size tenths", 0);
	if (v > 0) s_monoSize = std::clamp(v / 10, 8, 32);
}

static void SaveToRegistry() {
	VDRegistryAppKey key(kRegPath, true);
	key.setString("UI: Font family", VDTextU8ToW(s_uiFamily).c_str());
	key.setString("UI: Font weight", VDTextU8ToW(s_uiWeight).c_str());
	key.setInt("UI: Font point size tenths", s_uiSize * 10);

	key.setString("Console: Font family", VDTextU8ToW(s_monoFamily).c_str());
	key.setString("Console: Font weight", VDTextU8ToW(s_monoWeight).c_str());
	key.setInt("Console: Font point size tenths", s_monoSize * 10);
}

// =========================================================================
// Public API
// =========================================================================

static void DiscoverFonts() {
	// Discover fonts: embedded blobs first (always present, never fails),
	// then <exe_dir>/fonts/ for user-supplied additions, then CWD fallback.
	s_fontFiles.clear();

	// --- Embedded fonts (always available) ---
	{
		ATFontFile rec;
		rec.family       = "Roboto";
		rec.weight       = "Medium";
		rec.italic       = false;
		rec.monospaced   = false;
		rec.path         = "<builtin:roboto-medium>";
		rec.mpBuiltinData = g_atFontRobotoMediumData;
		rec.mBuiltinSize  = g_atFontRobotoMediumData_size;
		s_fontFiles.push_back(rec);

		rec.family       = "Fira Mono";
		rec.weight       = "Regular";
		rec.monospaced   = true;
		rec.path         = "<builtin:firamono-regular>";
		rec.mpBuiltinData = g_atFontFiraMonoRegularData;
		rec.mBuiltinSize  = g_atFontFiraMonoRegularData_size;
		s_fontFiles.push_back(rec);
	}

	// --- User-supplied additions: scan <exe>/fonts/, then CWD/fonts/. ---
	// Embedded fonts already cover the default experience; this is purely
	// for users who want extra families.  Both scans are best-effort.
	const size_t builtinCount = s_fontFiles.size();
	const char *base = SDL_GetBasePath();
	if (base && *base) {
		VDStringA dir(base);
		dir += "fonts";
		ScanFontDir(dir);
	}
	if (s_fontFiles.size() == builtinCount) {
		ScanFontDir(VDStringA("fonts"));
	}
	DiscoverSystemFonts();

	RebuildFamilyLists();

	LOG_INFO("UI", "Fonts: discovered %zu files, %zu UI families, %zu mono families",
		s_fontFiles.size(), s_uiFamilies.size(), s_monoFamilies.size());
	std::sort(s_fontFiles.begin() + builtinCount, s_fontFiles.end(),
		[](const ATFontFile& a, const ATFontFile& b) { return a.path < b.path; });
}

void ATUIFontsInit(float contentScale) {
	s_contentScale = contentScale > 0 ? contentScale : 1.0f;
	s_initialized = true;
#ifdef ATUI_HAVE_FREETYPE
	s_nativeRenderer = ATUIInitNativeFontRenderer();
	if (s_nativeRenderer)
		ImGui::GetIO().Fonts->SetFontLoader(ImGuiFreeType::GetFontLoader());
#endif
	DiscoverFonts();
	LoadFromRegistry();

	RebuildAtlas();
	s_dirty = false;
}

void ATUIFontsRebuildIfDirty() {
	if (!s_dirty || !s_initialized) return;
	s_dirty = false;

	// Clear() queues the old dynamic texture for destruction.  The active
	// renderer backend uploads the replacement during its next NewFrame.
	RebuildAtlas();
	SaveToRegistry();
}

ImFont *ATUIGetFontUI() {
	if (g_pFontUI)
		return g_pFontUI;
	return ImGui::GetIO().FontDefault;
}

ImFont *ATUIGetFontMono() {
	if (g_pFontMono)
		return g_pFontMono;
	if (g_pFontUI)
		return g_pFontUI;
	return ImGui::GetIO().FontDefault;
}

ImFont *ATUIGetFontIcon() {
	return g_pFontIcon; // may be null — callers must check before using
}

ImFont *ATUIGetFontHeading() {
	return s_fontHeading ? s_fontHeading : ATUIGetFontUI();
}

int ATUIFontsGetUISize() {
	return s_uiSize;
}

void ATUIFontsSetUISize(int pt) {
	if (pt < 8)  pt = 8;
	if (pt > 32) pt = 32;
	if (pt == s_uiSize) return;
	s_uiSize = pt;
	s_dirty = true;
}

// =========================================================================
// Configure System -> Emulator -> Fonts page
// =========================================================================

class ATSimulator;

// Lists all styles available for a given family, including italics.
static std::vector<VDStringA> CollectWeights(const char *family) {
	std::vector<VDStringA> out;
	for (const auto& f : s_fontFiles) {
		if (f.family != family) continue;
		if (std::find(out.begin(), out.end(), f.weight) == out.end())
			out.push_back(f.weight);
	}
	std::sort(out.begin(), out.end());
	return out;
}

static void RenderFamilyCombo(const char *label,
	const std::vector<VDStringA>& families,
	VDStringA& currentFamily,
	VDStringA& currentWeight, char (&filter)[128])
{
	if (families.empty()) {
		ImGui::TextDisabled("No compatible fonts found.");
		return;
	}
	ImGui::SetNextWindowSizeConstraints(ImVec2(300, 0), ImVec2(FLT_MAX, 420));
	ImGuiContext& g = *GImGui;
	const ImGuiID id = ImGui::GetID(label);
	const bool open = ImGui::BeginCombo(label, currentFamily.c_str(), ImGuiComboFlags_HeightLarge);
	// BeginCombo has no ItemInfo hook in ImGui 1.92. Keep this control
	// discoverable by the UI test engine like the sliders and buttons.
	IMGUI_TEST_ENGINE_ITEM_INFO(id, label, ImGuiItemStatusFlags_Openable
		| (open ? ImGuiItemStatusFlags_Opened : 0));
	if (open) {
		if (ImGui::IsWindowAppearing()) {
			filter[0] = 0;
			ImGui::SetKeyboardFocusHere();
		}
		ImGui::SetNextItemWidth(-1);
		ImGui::InputTextWithHint("##familyFilter", "Filter font families", filter, sizeof filter);
		ImGui::Separator();
		int matches = 0;
		for (const auto& family : families) {
			if (*filter && !SDL_strcasestr(family.c_str(), filter))
				continue;
			++matches;
			if (ImGui::Selectable(family.c_str(), family == currentFamily)) {
				currentFamily = family;
				auto weights = CollectWeights(family.c_str());
				if (std::find(weights.begin(), weights.end(), currentWeight) == weights.end()) {
					currentWeight = weights.empty() ? VDStringA("Regular") : weights.front();
					for (const char *normal : {"Regular", "Book", "Normal"})
						if (std::find(weights.begin(), weights.end(), VDStringA(normal)) != weights.end()) {
							currentWeight = normal;
							break;
						}
				}
				s_dirty = true;
			}
		}
		if (!matches) ImGui::TextDisabled("No matching families.");
		ImGui::EndCombo();
	}
	if (std::find(families.begin(), families.end(), currentFamily) == families.end())
		ImGui::TextDisabled("Selected family is unavailable; using a bundled font.");
}

static void RenderWeightCombo(const char *label, const char *family, VDStringA& currentWeight) {
	auto weights = CollectWeights(family);
	if (weights.empty()) return;

	std::vector<const char *> items;
	items.reserve(weights.size());
	for (const auto& w : weights) items.push_back(w.c_str());

	int idx = -1;
	for (size_t i = 0; i < weights.size(); ++i)
		if (weights[i] == currentWeight) { idx = (int)i; break; }
	if (idx < 0) {
		idx = 0;
		currentWeight = weights[0];
		s_dirty = true;
	}
	ImGuiContext& g = *GImGui;
	const ImGuiID id = ImGui::GetID(label);
	const bool changed = ImGui::Combo(label, &idx, items.data(), (int)items.size(), 16);
	IMGUI_TEST_ENGINE_ITEM_INFO(id, label, ImGuiItemStatusFlags_None);
	if (changed) {
		currentWeight = weights[idx];
		s_dirty = true;
	}
}

void RenderFontsCategory(ATSimulator &) {
	static char uiFilter[128] {}, monoFilter[128] {};
	ImGui::TextWrapped(
		"Choose an installed or bundled font. Use the family filter to find a font "
		"quickly; styles and sizes apply immediately and are saved automatically.");
	ImGui::TextDisabled("%zu font families / %zu monospace families", s_uiFamilies.size(), s_monoFamilies.size());
	if (ImGui::Button("Refresh font list")) {
		DiscoverFonts();
		s_dirty = true;
	}
	ImGui::SetItemTooltip("Reload installed fonts and the fonts folder next to the executable.");
	ImGui::Spacing();

	// ----- UI Font -----
	ImGui::SeparatorText("UI Font");
	ImGui::TextDisabled("Used for menus, dialogs, and text in the emulator UI.");
	RenderFamilyCombo("Family##ui", s_uiFamilies, s_uiFamily, s_uiWeight, uiFilter);
	RenderWeightCombo("Style##ui", s_uiFamily.c_str(), s_uiWeight);
	if (ImGui::SliderInt("Size (pt)##ui", &s_uiSize, 8, 32, "%d pt")) {
		s_dirty = true;
	}
	ImGui::SetItemTooltip("Drag or click; the change applies on the next frame.");

	// Live preview using the currently active font (rebuilt at end of frame).
	if (g_pFontUI) {
		ImGui::PushFont(ATUIGetFontHeading(), ImGui::GetStyle().FontSizeBase * 1.2f);
		ImGui::TextUnformatted("Actions and settings");
		ImGui::PopFont();
		ImGui::PushFont(g_pFontUI);
		ImGui::TextWrapped("The quick brown fox jumps over the lazy dog. 0123456789");
		ImGui::PopFont();
	}
	ImGui::Spacing();

	// ----- Monospace Font -----
	ImGui::SeparatorText("Monospace Font");
	ImGui::TextDisabled(
		"Used for the debugger panes (disassembly, memory, history, console).");
	RenderFamilyCombo("Family##mono", s_monoFamilies, s_monoFamily, s_monoWeight, monoFilter);
	RenderWeightCombo("Style##mono", s_monoFamily.c_str(), s_monoWeight);
	if (ImGui::SliderInt("Size (pt)##mono", &s_monoSize, 8, 32, "%d pt")) {
		s_dirty = true;
	}

	if (g_pFontMono) {
		ImGui::PushFont(g_pFontMono);
		ImGui::TextUnformatted("Preview: lda $D01A   ; 0xDEADBEEF  iiii  WWWW  ....");
		ImGui::PopFont();
	}
	ImGui::Spacing();

	// ----- Reset -----
	ImGui::Separator();
	if (ImGui::Button("Reset to Defaults")) {
		s_uiFamily   = kDefaultUIFamily;
		s_uiWeight   = kDefaultUIWeight;
		s_uiSize     = kDefaultUISize;
		s_monoFamily = kDefaultMonoFamily;
		s_monoWeight = kDefaultMonoWeight;
		s_monoSize   = kDefaultMonoSize;
		s_dirty = true;
	}
	ImGui::SameLine();
	ImGui::TextDisabled("Roboto Medium %d pt / Fira Mono Regular %d pt", kDefaultUISize, kDefaultMonoSize);
}
